#!/usr/bin/env bash
# Build a Ganatri development-progress HTML+PDF report from repo state.
# Used as a CI fallback when the Claude report-generator step produces nothing.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

python3 <<'PY'
import html
import re
import subprocess
from datetime import datetime
from pathlib import Path

ROOT = Path.cwd()
STATE = ROOT / "docs/nightly/STATE.md"
PLAN = ROOT / "docs/DEVELOPMENT_PLAN.md"


def section(text: str, heading: str) -> str:
    lines = text.splitlines()
    out: list[str] = []
    capture = False
    for line in lines:
        if line.startswith("## "):
            if capture:
                break
            capture = line[3:].strip() == heading
            continue
        if capture:
            out.append(line.rstrip())
    return "\n".join(out).strip()


def priority_queue(plan: str) -> list[str]:
    start = "<!-- PRIORITY_TODO:START -->"
    end = "<!-- PRIORITY_TODO:END -->"
    if start not in plan or end not in plan:
        return []
    body = plan.split(start, 1)[1].split(end, 1)[0]
    items = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("- ["):
            items.append(stripped)
    return items


def test_summary(plan: str) -> str:
    for line in plan.splitlines()[:60]:
        if "tests passing" in line.lower() or "tests pass" in line.lower():
            return line.strip()
    return "See docs/DEVELOPMENT_PLAN.md for current test counts."


def branch_commits() -> list[str]:
    result = subprocess.run(
        ["git", "log", "origin/main..HEAD", "--oneline", "-8"],
        capture_output=True,
        text=True,
        check=False,
    )
    lines = [ln for ln in result.stdout.splitlines() if ln.strip()]
    return lines or ["No commits on this branch yet (work may be in progress or unchanged)."]


def find_chrome() -> str | None:
    for name in ("google-chrome", "google-chrome-stable", "chromium-browser", "chromium"):
        path = subprocess.run(["bash", "-lc", f"command -v {name}"], capture_output=True, text=True)
        candidate = path.stdout.strip()
        if candidate:
            return candidate
    return None


state_text = STATE.read_text(encoding="utf-8")
plan_text = PLAN.read_text(encoding="utf-8")

phase = section(state_text, "Current Phase") or "Unknown"
status = re.sub(r"<!--.*?-->", "", section(state_text, "Status") or "Unknown").strip()
last_run = section(state_text, "Last Run") or "No last-run entry."
blockers = section(state_text, "Blockers / Needs Human Input") or "(none)"
notes = section(state_text, "Notes for Next Run") or "(none)"
queue = priority_queue(plan_text)
tests = test_summary(plan_text)
commits = branch_commits()
today = datetime.now().strftime("%B %d, %Y")
ts = datetime.now().strftime("%Y%m%d-%H%M")
slug = "ganatri-development-progress"

queue_html = ""
if queue:
    queue_html = "<ul>" + "".join(f"<li>{html.escape(item)}</li>" for item in queue) + "</ul>"
else:
    queue_html = "<p>Priority queue empty — nightly follows normal phase flow.</p>"

commits_html = "<ul>" + "".join(f"<li><code>{html.escape(c)}</code></li>" for c in commits) + "</ul>"

body = f"""
<div class="eyebrow">Nightly development report</div>
<h1 class="title">Ganatri — <span class="accent">Development Progress</span></h1>
<p class="subtitle">Automated snapshot for <strong>{html.escape(today)}</strong> (CI fallback generator).</p>

<div class="callout"><strong>Current phase.</strong> {html.escape(phase)}<br><strong>Status.</strong> {html.escape(status)}</div>

<div class="section-eyebrow">Last run</div>
<div class="callout"><pre class="mono">{html.escape(last_run)}</pre></div>

<div class="section-eyebrow">Priority queue</div>
<div class="callout">{queue_html}</div>

<div class="section-eyebrow">This branch</div>
<div class="callout">{commits_html}</div>

<div class="section-eyebrow">Tests</div>
<div class="callout">{html.escape(tests)}</div>

<div class="section-eyebrow">Blockers</div>
<div class="callout"><pre class="mono">{html.escape(blockers)}</pre></div>

<div class="section-eyebrow">Notes for next run</div>
<div class="callout"><pre class="mono">{html.escape(notes)}</pre></div>

<div class="note"><span class="arrow">→</span><span>Generated by .github/scripts/generate-nightly-report.sh when Claude did not produce reports/.</span></div>
"""

css = """
:root{--bg:#FAF8F3;--surface:#ECE5D8;--surface-2:#E5DDCD;--line:#DAD3C6;--ink:#1C1A17;--text:#57534C;--muted:#8A857C;--accent:#E07B5C;--accent-deep:#D2693F;}
*{box-sizing:border-box;margin:0;padding:0;}
@page{size:A4;margin:0 0 60px 0;}
@page{@bottom-center{content:counter(page) " / " counter(pages);color:var(--accent);font-family:monospace;font-size:11px;}}
html,body{background:var(--bg);}
body{font-family:Inter,system-ui,sans-serif;color:var(--text);font-size:14px;line-height:1.5;-webkit-print-color-adjust:exact;print-color-adjust:exact;}
.page{max-width:760px;margin:0 auto;padding:64px 48px 0;}
.eyebrow{font-size:12px;font-weight:700;letter-spacing:.15em;text-transform:uppercase;color:var(--accent);text-align:center;}
.title{font-family:Georgia,serif;font-weight:800;font-size:44px;line-height:1.05;color:var(--ink);text-align:center;margin:14px 0 16px;}
.title .accent{color:var(--accent);}
.subtitle{font-size:16px;color:var(--muted);text-align:center;max-width:560px;margin:0 auto 8px;}
.subtitle strong{color:var(--ink);}
.section-eyebrow{font-size:12px;font-weight:700;letter-spacing:.15em;text-transform:uppercase;color:var(--accent);margin:32px 0 16px;}
.callout{background:var(--surface);border-radius:14px;padding:16px 18px;font-size:13px;line-height:1.5;margin-top:8px;}
.callout strong{color:var(--ink);}
.callout ul{margin:8px 0 0 18px;}
.callout pre.mono,.callout .mono{font-family:monospace;font-size:12px;white-space:pre-wrap;word-break:break-word;}
code{font-family:monospace;font-size:.92em;background:var(--surface-2);padding:1px 6px;border-radius:5px;}
.note{display:flex;gap:10px;color:var(--muted);font-size:12px;margin:32px 0 24px;}
.note .arrow{color:var(--accent);font-weight:700;}
"""

document = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Ganatri — Development Progress</title>
<style>{css}</style>
</head>
<body>
<div class="page">
{body}
</div>
</body>
</html>
"""

reports = ROOT / "reports"
reports.mkdir(exist_ok=True)
html_path = reports / f"{slug}-{ts}.html"
pdf_path = reports / f"{slug}-{ts}.pdf"
html_path.write_text(document, encoding="utf-8")
print(f"generate-nightly-report: wrote {html_path}")

chrome = find_chrome()
if chrome:
    cmd = [
        chrome,
        "--headless=new",
        "--disable-gpu",
        "--no-pdf-header-footer",
        "--virtual-time-budget=10000",
        f"--print-to-pdf={pdf_path.resolve()}",
        f"file://{html_path.resolve()}",
    ]
    subprocess.run(cmd, check=True)
    print(f"generate-nightly-report: wrote {pdf_path}")
else:
    print("generate-nightly-report: no Chrome/Chromium found — HTML only", flush=True)
PY
