-- Ganatri initial schema migration
-- Generated by Drizzle Kit

-- Create ENUM types
CREATE TYPE "room_status" AS ENUM ('LOBBY', 'PLAYING', 'DONE', 'ABANDONED');
CREATE TYPE "game_event_type" AS ENUM ('GAME_STARTED', 'PLAYER_PLAYED', 'CAPTURED', 'CARD_DRAWN', 'TRICK_WON', 'CUT', 'PLAYER_SAFE', 'GAME_OVER', 'PLAYER_DISCONNECTED', 'PLAYER_RECONNECTED');

-- Users table
CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "display_name" varchar(100) NOT NULL,
  "email" varchar(255) UNIQUE,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_at" timestamp with time zone NOT NULL DEFAULT now(),
  "is_guest" boolean NOT NULL DEFAULT true
);

CREATE INDEX "users_email_idx" ON "users"("email");

-- Rooms table
CREATE TABLE "rooms" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "room_code" varchar(6) NOT NULL UNIQUE,
  "host_user_id" uuid NOT NULL,
  "status" "room_status" NOT NULL DEFAULT 'LOBBY',
  "config_snapshot" jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "closed_at" timestamp with time zone,
  FOREIGN KEY ("host_user_id") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "rooms_room_code_idx" ON "rooms"("room_code");
CREATE INDEX "rooms_status_idx" ON "rooms"("status");

-- Games table
CREATE TABLE "games" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "room_id" uuid NOT NULL,
  "seed" integer NOT NULL,
  "seating_order" jsonb NOT NULL,
  "player_count" integer NOT NULL,
  "config_snapshot" jsonb,
  "started_at" timestamp with time zone NOT NULL,
  "ended_at" timestamp with time zone,
  "duration_ms" integer,
  "winner_id" uuid,
  "is_abandoned" boolean NOT NULL DEFAULT false,
  FOREIGN KEY ("room_id") REFERENCES "rooms"("id"),
  FOREIGN KEY ("winner_id") REFERENCES "users"("id")
);

CREATE INDEX "games_room_id_idx" ON "games"("room_id");
CREATE INDEX "games_winner_id_idx" ON "games"("winner_id");
CREATE INDEX "games_started_at_idx" ON "games"("started_at");

-- Game Players table (join table)
CREATE TABLE "game_players" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "game_id" uuid NOT NULL,
  "user_id" uuid,
  "seat_index" integer NOT NULL,
  "display_name_snapshot" varchar(100) NOT NULL,
  "final_rank" integer,
  "was_cut" boolean NOT NULL DEFAULT false,
  "capture_count" integer NOT NULL DEFAULT 0,
  "result" varchar(20),
  FOREIGN KEY ("game_id") REFERENCES "games"("id"),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);

CREATE INDEX "game_players_game_id_idx" ON "game_players"("game_id");
CREATE INDEX "game_players_user_id_idx" ON "game_players"("user_id");

-- Game Events table (move log)
CREATE TABLE "game_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "game_id" uuid NOT NULL,
  "seq" integer NOT NULL,
  "ts" timestamp with time zone NOT NULL,
  "actor_user_id" uuid,
  "event_type" "game_event_type" NOT NULL,
  "payload" jsonb NOT NULL,
  FOREIGN KEY ("game_id") REFERENCES "games"("id"),
  FOREIGN KEY ("actor_user_id") REFERENCES "users"("id")
);

CREATE INDEX "game_events_game_id_idx" ON "game_events"("game_id");
CREATE UNIQUE INDEX "game_events_game_id_seq_idx" ON "game_events"("game_id", "seq");
CREATE INDEX "game_events_actor_user_id_idx" ON "game_events"("actor_user_id");

-- Player Stats table (aggregate)
CREATE TABLE "player_stats" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL UNIQUE,
  "games_played" integer NOT NULL DEFAULT 0,
  "games_won" integer NOT NULL DEFAULT 0,
  "games_lost" integer NOT NULL DEFAULT 0,
  "games_abandoned" integer NOT NULL DEFAULT 0,
  "total_captures" integer NOT NULL DEFAULT 0,
  "cuts_given" integer NOT NULL DEFAULT 0,
  "cuts_received" integer NOT NULL DEFAULT 0,
  "times_safe" integer NOT NULL DEFAULT 0,
  "total_play_time_ms" integer NOT NULL DEFAULT 0,
  "longest_win_streak" integer NOT NULL DEFAULT 0,
  "current_win_streak" integer NOT NULL DEFAULT 0,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
);

CREATE UNIQUE INDEX "player_stats_user_id_idx" ON "player_stats"("user_id");
